# POST http://localhost:8000/todos/create http/1.1
# Content-Type: application/json 

# {
#     "todo_description": "My first todo",
#     "todo_responsible": "Sebastian",
#     "todo_priority": "Medium"
# }

POST http://localhost:8000/todos/edit/5f205b1f1248850760761396
# Content-Type: application/json 

{ 
     "todo_description": "My first todo",
     "todo_responsible": "Aanyu Deborah",
     "todo_priority": "Medium"   
}
